# Use the official Node.js image as a base image
FROM node:18


WORKDIR /app


COPY package.json package-lock.json ./


RUN yarn install

RUN yarn add --dev nodemon


COPY src ./src
COPY public ./public

EXPOSE 3000

CMD ["yarn", "start"]
